project:
  type: website
  output-dir: docs

website:
  title: "Elizabeth Miller"
  navbar:
    search: true
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - text: "Mapping and Data Analysis"
        menu: 
          - upp462.qmd
          - finalproj.Rmd
      - text: "Urban Design"
        menu:
          - nicollet.qmd
          - imd.qmd
          - encuentro.qmd
      - text: "Writing"
        menu: 
          - imdreport.qmd
          - evanston.qmd
          - lfnc.qmd
          - capstone.qmd
      - text: "Animation"
        menu: 
          - urbanrenewal.qmd
          - gifs.qmd

format:
  html:
    theme: lux
    mainfont: "Helvetica"
    fontsize: 1.1em
    fontcolor: "#181616"
    linkcolor: "#C23B27"
    css: styles.css
    toc: true

editor: visual

