project:
  type: website
  output-dir: docs

website:
  title: "Elizabeth Miller"
  navbar:
    search: true
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - text: "Mapping and Data Visualization"
        menu: 
          - collages.qmd
      - text: "Animation"
        menu: 
          - urbanrenewal.qmd
          - gifs.qmd
      - text: "Urban Design"
        menu:
          - nicollet.qmd
          - imd.qmd

format:
  html:
    theme: lux
    mainfont: roboto
    fontsize: 1.1em
    fontcolor: "#181616"
    linkcolor: "#C23B27"
    css: styles.css
    toc: true

editor: visual

