project:
  type: website
  output-dir: docs

website:
  title: "Elizabeth Miller"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd

format:
  html:
    theme: lux
    mainfont: roboto
    fontsize: 1.1em
    fontcolor: "#181616"
    linkcolor: "#C23B27"
    css: styles.css
    toc: true

editor: visual

