---
title: "Lead for North Carolina Blog Post"
subtitle: "Water, Water Everywhere"
---

*I wrote this blog post during my time in Hyde County, North Carolina as a Lead For North Carolina Americorps member to reflect on my experiences working in housing and grant administration in a rural, coastal county.*

Over the past few months, I have been administering a grant for urgent housing repairs to low-income households in Hyde County. I took over the project in late August from the previous grant administrator, who left the county before I began my fellowship. When she left, virtually all internal institutional knowledge of the grant vanished. The county had never received this grant before, so any chance of the county receiving this much-needed support again hinged on my successful completion of the project. With three months left in the project, I was tasked with overseeing 10 construction projects from bidding to completion while also bringing the project into compliance with the grant guidelines. I had never managed any construction projects before and had never administered a grant. The list of challenges that ensued is too lengthy to enumerate here, but the project followed Murphy’s Law: anything that could have gone wrong went wrong. The grant is in the monitoring stage now, so time will tell if my efforts were sufficient. At the end of the day, there are homeowners in the county who are able to sleep a little more soundly because of these home improvements.

Not only did this project provide me with one of the most arduous, stressful, and rewarding learning experiences of my life, but it also demonstrated to me the interlocking nature of Hyde County’s struggles. This blog post serves as a wide-ranging, at times rambling, reflection on this process and its implications.

The purpose of the grant I administered is to address urgent needs – deteriorated parts of the house that could make the house uninhabitable, causing someone to relocate or, in a worst-case scenario, be injured or killed. Such repairs can allow someone to remain in their home when they would have otherwise had to leave the county to live with family or an assisted living facility. In a jurisdiction like Hyde, which is facing the dual specters of population loss and climate change, every household that stays in the county matters. Not only do the residents remain connected to the communities and land that raised them, but the county also maintains a tax base and a raison d’être.

All the recipients of these urgent repairs are elderly, single women who live alone or who serve as the primary caretaker of others in their household. When asked about their experience living in Hyde County, almost every woman told me, “There’s no place like home.” Some had lived in the county all their lives; some had returned after years of living elsewhere. Almost all were born there, and many within a 10-mile radius of their current home. Every homeowner had a unique knowledge of the land and history. Each could tell me exactly where water drained from their yard (one colleague told me of an interesting housing/drainage dynamic I had never considered: low-income residents who live near large farms often have better drainage than those who do not because farmers must invest in more sophisticated drainage measures to prevent crop loss and secure profits).

Many of the repairs pertained to water or flood damage of some kind – a leaking roof, floors from rotting flooding damage, etc. – which comes as no surprise to anyone familiar with the geography or socio-environmental history of Hyde County. Water is everywhere, pervades all discussions. Perhaps the county’s biggest claim to water fame was the draining of Lake Mattamuskeet – the state’s largest natural lake – to farm in the nutrient-rich lakebed in the 1800s. The lake has since filled back in with water after pumping ended in the 1930s. The pumping station remains an attraction, and the lake is now a destination for wildlife, birders, and hunters. Canals and dikes are the county’s legacy. One homeowner I spoke with discussed how the drainage ditch near her house used to be cleared regularly, but now, she has noticed that many of the ditches throughout the county do not receive the necessary maintenance.

“Sustainable construction” often conjures images of sleek skyscrapers, new builds with LEED certification, and plant walls. While these are all well and good, upfitting the buildings we already have is frequently the more sustainable option. To frame my work on housing repairs, I return to [this article ](https://placesjournal.org/article/maintenance-and-care/) in Places Journal by Sharon Mattern on maintenance and care. This project was often discouraging. The list of homeowners who needed support was lengthy, and even the homeowners who received repairs had additional housing needs not met by the grant. Moreover, renters did not even qualify for the grant. Once, I was meeting with my county manager to discuss a particularly difficult challenge and my nose started bleeding (she claims from stress) in her office. Viewing these repairs through an ethic of maintenance and care, however, helped me gain an appreciation for the outcomes of the project, even if they seem like small potatoes. We know that systems tend toward chaos, erosion, decay, and breakdown, and we are tasked with, as Mattern says, studying “how the world gets put back together.” The repair of some leaky roofs, front steps, floors, and windows in rural North Carolina is helping to put a tiny bit of the world back together.

Of course, when it rains, it pours, and as this project drew to a close, we learned that the regional housing authority was closing an affordable housing development in the county, displacing several families and long-term residents. Such a population loss is significant in a county with fewer than 5,000 residents. Building new housing on the mainland is difficult because so much of the land in the county is either farmland or protected lands. Housing on Ocracoke presents its own challenges associated with climate change, housing seasonal workers, and vacation rentals.

Some people like to joke that the county is 10 years behind the rest of the state. I think, for better or for worse, the county is 10 years ahead of many places in its resilience to climate change. County residents across the political spectrum are acutely aware of the threat of climate change because they are already living it – saltwater intrusion into farmland, flooding, hurricanes. As we near hurricane season, my coworkers are bracing for another big storm. September will mark the third year since Hurricane Dorian, and my colleagues have emphasized that we are overdue for another one. This underlines the pervasive housing struggle – what of the existing housing stock is equipped to withstand another storm? How many residents would have to relocate to another jurisdiction if their home is destroyed in a hurricane?

Much attention has been paid to housing crises in urban cores, and rightfully so, but concern is owed to rural residents as well. I find it difficult to articulate a response or solution that does not require a massive restructuring of society. Burnt-out county employees can only achieve so much. I find solace, however, in this quote from author Ursula K. Le Guin: “We live in capitalism. Its power seems inescapable. So did the divine right of kings. Any human power can be resisted and changed by human beings. Resistance and change often begin in art, and very often in our art, the art of words.”
